/*
 *   Pouch.h
 *   - pouch container commands
 */
#ifndef XV6_POUCH_H
#define XV6_POUCH_H

typedef enum p_cmd {
  START,
  CONNECT,
  DISCONNECT,
  DESTROY,
  LIMIT,
  INFO,
  LIST,
  IMAGES,
  BUILD,
} p_cmd;

typedef enum POUCH_INTERNAL_STATUS_CODES {
  SUCCESS_CODE = 0,
  END_OF_FILE_CODE = 1,
  // Error codes < 0
  ERROR_CODE = -1,
  ERROR_IMAGE_NAME_TOO_LONG_CODE = -2,
  ERROR_IMAGE_NOT_FOUND_CODE = -3,
  ERROR_OUT_OF_MEMORY_CODE = -4,
  ERROR_INVALID_IMAGE_NAME_CODE = -5,
  ERROR_IMAGE_DIR_INVALID_CODE = -6,
  ERROR_IMAGE_INVALID_CODE = -7,
  CONTAINER_NAME_TOO_LONG_CODE = -8,
  TTY_CLOSE_ERROR_CODE = -9,
  TTY_DISCONNECT_ERROR_CODE = -10,
  TTY_DETACH_ERROR_CODE = -11,
  TTY_OPEN_ERROR_CODE = -12,
  TTY_CONNECT_ERROR_CODE = -13,
  KILL_CONTAINER_PROC_ERROR_CODE = -14,
  CONTAINER_NOT_FOUND_CODE = -15,
  POUCH_MUTEX_ERROR_CODE = -16,
  UNSAHRE_MNT_NS_FAILED_ERROR_CODE = -17,
  IMAGE_MOUNT_FAILED_ERROR_CODE = -18,
  CONTAINER_ALREADY_STARTED_CODE = -19,
  UNSAHRE_PID_NS_FAILED_ERROR_CODE = -20,
  POUCH_FORK_FAILED_ERROR_CODE = -21,
  CGROUP_CREATE_FAILED_CODE = -22,
  MOUNT_CGROUP_FAILED_ERROR_CODE = -23,
  NO_AVAILABLE_TTY_ERROR_CODE = -24,
  INVALID_CCONF_ERROR_CODE = -25,
  INVALID_CCONF_TO_WRITE_ERROR_CODE = -26,
  FAILED_TO_OPEN_CCONF_ERROR_CODE = -27,
} pouch_status;

#endif /* XV6_POUCH_H */
