name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare environment
      run: sudo apt-get install -y expect qemu-system-x86

    - name: Cleanup
      run: make clean

    - name: Build
      run: make TEST=1

    - name: Test
      run: ./runtests.exp mylog

